In [19]:
#NumPyモジュールをnpという名前で利用する
import numpy as np

print("\n-----▼NumPyの一次元配列を生成-------------")
a = np.array([1,2,3,4,5])
print(a)
print(type(a)) #オブジェクト名

print("\n-----▼NumPyの二次元配列を生成-------------")
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

print("\n-----▼NumPyで0初期化-------------")
print(np.zeros(10))
print(np.zeros((3,2)))


print("\n-----▼NumPyで連番で初期化-------------")
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(5,8,0.5))


print("\n-----▼NumPyで行列計算-------------")
a = np.array([1,2,3,4,5]) #初期化
b = a * 2 #計算
print(b)

print("\n-----▼NumPyで行列計算-------------")
x = np.arange(10)
y = 3*x+5
print(y)

print("\n-----▼NumPyで配列の次元数を調べる-------------")
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.shape)

print("\n-----▼NumPyで配列の次元数を変換する-------------")
a = np.array([[1,2,3],[4,5,6]])
print("a=",a)
b = a.flatten()
print("b=",b)

print("\n-----▼NumPyで配列の次元数を変換する-------------")
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.reshape(3,2))

print("\n-----▼NumPyで配列の要素にアクセスする-------------")
v=np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]       # vから0番目
b = v[1:]      # vから1以降の要素を取り出す
c = v[:, 0]    # vから二次元配列の各0番目の要素を取り出す 例）1列目を取得
print("a=",a)
print("b=",b)
print("c=",c)


-----▼NumPyの一次元配列を生成-------------
[1 2 3 4 5]
<class 'numpy.ndarray'>

-----▼NumPyの二次元配列を生成-------------
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

-----▼NumPyで0初期化-------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]

-----▼NumPyで連番で初期化-------------
[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]

-----▼NumPyで行列計算-------------
[ 2  4  6  8 10]

-----▼NumPyで行列計算-------------
[ 5  8 11 14 17 20 23 26 29 32]

-----▼NumPyで配列の次元数を調べる-------------
(2, 3)
(3, 3)

-----▼NumPyで配列の次元数を変換する-------------
a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]

-----▼NumPyで配列の次元数を変換する-------------
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]

-----▼NumPyで配列の要素にアクセスする-------------
a= [1 2 3]
b= [[4 5 6]
 [7 8 9]]
c= [1 4 7]
